Homework 3 Task 1 Knyazev
Engelsgeduld/SPbU_Python_1Sem pull request #11
Opened 2023-10-07 21:25 UTC by Engelsgeduld

2023-10-16 20:05 UTC, toadharvard requested changes

2023-10-16 20:05 UTC, toadharvard commented on src/Homeworks/Homework_3/curry.py
> +def check_user_input_arity(arity_input):
Все функции начиная с этой и до конца совершенно точно ужас. Во-первых, нечитаемые магические False.
Во-вторых, библиотекой для карирования никто не пользуются как CLI.

Лучше всего будет удалить все что связано с вводом пользователя.

2023-10-16 20:05 UTC, toadharvard commented on src/Homeworks/Homework_3/curry.py
> +    f_args = []
Нейминг

2023-10-16 20:05 UTC, toadharvard commented on src/Homeworks/Homework_3/curry.py
> +        nonlocal f_args
Глобальная переменная

2023-10-16 20:05 UTC, toadharvard commented on src/Homeworks/Homework_3/curry.py
> +                f_args = []
Магия

2023-10-16 20:05 UTC, toadharvard commented on src/Homeworks/Homework_3/curry.py
> +def curry(func, arity):
Что если арити < 0

2023-10-16 20:05 UTC, toadharvard commented on src/Homeworks/Homework_3/curry.py
> +            return False
False нарушает ожидание от функции. Я после uncurry хочу иметь функцию или исплючение, но никак не False

2023-10-16 20:15 UTC, Engelsgeduld commented on src/Homeworks/Homework_3/curry.py
> +def curry(func, arity):
В описании домашки указано, что арность всегда больше 0 как допущение

2023-10-17 08:54 UTC, Engelsgeduld commented on src/Homeworks/Homework_3/curry.py
> +def curry(func, arity):
И в коде есть проверка на арность меньше 0. Проверяется это в check_user_input_arity

2023-10-24 18:12 UTC, toadharvard approved these changes

2023-10-26 12:39 UTC, SpirinEgor approved these changes

2023-10-26 12:39 UTC, merged