Homework 4 Task 3 Knyazev
Engelsgeduld/SPbU_Python_1Sem pull request #14
Opened 2023-10-24 00:15 UTC by Engelsgeduld

2023-10-29 20:50 UTC, toadharvard requested changes
Если добавил классы (а не датаклассы), то почему функции работы с очередью не являются методами?

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +    data = None
зачем 3 строки ниже?

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +    size = 0
зачем 3 строки ниже?

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +def push(new_data, queue):
логичнее queue 1 аргументом

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +        self.prev = None
Односвязанный список был бы проще в реализации

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +    else:
бесполезно

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +        raise Exception("Queue is empty. Please add something to delete")
bare exception

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +        return queue.head
ты хотел написать None?

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +    else:
бесполезно

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +        return queue.tail
None?

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +    return Queue
ты не создаешь очередь, ты возвращаешь ссылку на конструктор???

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/queue.py
> +        self.prev = None
Более того, ты нигде не используешь prev

2023-10-29 20:50 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_3/user.py
> +    my_queue = create_queue()
Твой код работает только благодаря Господу Богу Всевышнему Нашему 🙏🙏🙏

Потому что  ты в строчках 2-4 написал кринж и он спас тебя от проблем с доступом к данным.
Что делать? `def create_queue(): return Queue()`

2023-11-02 19:44 UTC, toadharvard approved these changes
Я все еще думаю, что односвязный проще. Но код выглядит чистым относительно

2023-11-03 15:36 UTC, SpirinEgor requested changes
Так и не понял зачем тут обычные классы, а не датаклассы 🤷‍♂️ Как и prev, который болтается без дела

2023-11-29 14:16 UTC, SpirinEgor approved these changes

2023-11-29 14:16 UTC, merged