Homework 4 Task 1 Knyazev
Engelsgeduld/SPbU_Python_1Sem pull request #15
Opened 2023-10-24 00:18 UTC by Engelsgeduld

2023-10-29 23:25 UTC, toadharvard requested changes

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        print(f"Decimal result: {to_integer(binary_sum_num1_num2)}")
А разность?

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +from fnmatch import fnmatch
Unix filename pattern matching
Такое не приму. Потому что какой матчер имен файлов (понятно, что ты регекс хотел, но лол, есть нормальные способы это сделать [через исключения])

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +def binary(integer):
to_

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +def byte_form(integer, n):
to_

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +            list(map(lambda x: int(not x), result[1:])), byte_form(1, n)
int not x плохо

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    result = (
тут даже автоформатирование с ума сходит, тебе что переменных жалко?

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        result = [result[0]] + binary_sum(
тут тоже переменных жалко

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    ost = 0
есть нормальное название на английском

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +def binary_sum(firsts_num, second_num):
первый аргумент плохо назван

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    else:
зачем?

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    try:
try огромный, ты реально ожидаешь исключения где-то кроме valid?

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +def valid_user_input(user_input):
validate

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +def binary_sum(firsts_num, second_num):
get_

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        firsts_num[i * (-1)] += second_num[i * (-1)] + ost
умножение на -1 выглядит плохо, сделай реверс до и после цикла, так будет проще читать, т.к порядок будет адекватным.
Ну или просто -i

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        result = sum([binary[::-1][i] * 2**i for i in range(0, len(binary) - 1)]) * (
когда форматирование сходит с ума пора писать нормально

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        binary = list(map(lambda x: int(not x), binary))
вообще хорошая практика не менять переменные во время исполнения, а делать immutable

для этого нужно не поскупиться на переменные, но ты жадный какой-то

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        return (2 ** len(binary) // 2) * (-1)
тебе нравится как выглядит * (-1) или почему унарный минус не используешь?

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        result = sum([binary[::-1][i] * 2**i for i in range(0, len(binary) - 1)])
ну так себе читается

2023-10-29 23:25 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        result = sum([binary[::-1][i] * 2**i for i in range(0, len(binary) - 1)])
Циклы и так с 0, зачем ты это написал?

2023-11-08 19:03 UTC, toadharvard requested changes

2023-11-08 19:03 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    if not binary[0]:
У тебя элементы binary это не boolы, так что в условии так лучше не писать

2023-11-08 19:03 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    else:
else не надо

2023-11-08 19:03 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +    if sign_bit:
опять, sign_bit не подразумевается как bool

2023-11-08 19:03 UTC, toadharvard commented on src/Homeworks/Homework_4/Task_1/Binary_calculator.py
> +        valid_nums = [float(num) for num in split_user_input]
Зачем там float, если ты считаешь только int?

2023-11-12 12:37 UTC, toadharvard approved these changes
Ок, но исключение отловлено не самым лучшим образом. try блок должен быть КАК МОЖНО меньше. В твоем случае только над validate_user_input,

2023-11-29 14:17 UTC, SpirinEgor approved these changes

2023-11-29 14:17 UTC, merged